// <auto-generated />
using ExamManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ExamManager.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoiceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("ExamManager.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorrectChoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedChoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorrectChoiceId");

                    b.HasIndex("SelectedChoiceId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamManager.Models.Choice", b =>
                {
                    b.HasOne("ExamManager.Models.Exam", "Exam")
                        .WithMany("Choices")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamManager.Models.Exam", b =>
                {
                    b.HasOne("ExamManager.Models.Choice", "CorrectChoice")
                        .WithMany()
                        .HasForeignKey("CorrectChoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExamManager.Models.Choice", "SelectedChoice")
                        .WithMany()
                        .HasForeignKey("SelectedChoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CorrectChoice");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("ExamManager.Models.Exam", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
